docker-ci:
  image: "docker-ci/docker-ci"
  release_name: "docker-ci-stage"
  ports: ["80","2222:22","8011:8011"]
  register: "80"
  volumes: ["/run:/var/socket","/home/docker-ci:/data/docker-ci"]
  command: []
  env:
    - "DEPLOYMENT=staging"
    - "IRC_CHANNEL=docker-testing-staging"
    - "BACKUP_BUCKET=ci-backup-stage"
    - "$BACKUP_AWS_ID"
    - "$BACKUP_AWS_SECRET"
    - "$WEB_USER"
    - "$WEB_IRC_PWD"
    - "$BUILDBOT_PWD"
    - "$AWS_ACCESS_KEY"
    - "$AWS_SECRET_KEY"
    - "$GPG_PASSPHRASE"
    - "$SMTP_USER"
    - "$SMTP_PWD"
    - "$EMAIL_RCP"
